---
- name: Install Filebeat
  hosts: web
  become: yes
  gather_facts: true
  vars:
    kibana_host: 192.168.4.3:5601
    elastic_host: 192.168.3.4:9200
  tasks:
  - name: Install filebeat
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.27-amd64.deb"

  - name: Copy config filebeat
    template:
      src: /home/wah3299/ansible/filebeat.j2
      dest: /etc/filebeat/filebeat.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name: reload filebeat and autorun
    service:
      name: filebeat
      state: restarted
      enabled: yes
